CREATE TABLE "features" ("Id" INTEGER PRIMARY KEY  NOT NULL , "Name" TEXT NOT NULL );
CREATE TABLE "files" ("Path" TEXT PRIMARY KEY  NOT NULL  UNIQUE , "ObjectId" INTEGER NOT NULL , "FeatureId" INTEGER NOT NULL);
CREATE TABLE "objects" ("Id" INTEGER PRIMARY KEY  NOT NULL , "Hash" VARCHAR NOT NULL  UNIQUE, "Size" INTEGER NOT NULL );
CREATE TABLE "packages" ("Id" INTEGER PRIMARY KEY  NOT NULL , "Name" VARCHAR NOT NULL  UNIQUE, "Size" INTEGER NOT NULL );
CREATE TABLE "storage_mapping" ("ObjectId" INTEGER NOT NULL , "PackageId" INTEGER NOT NULL );
